# -*- coding: utf-8 -*-
"""Project_Prototype.pynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15KgT58FNZWa2_SKdfXYFQHq6Z3MUxWia

### 1) Baseline Model

*   TF-IDF and logistic regression
*   Metric: Macro-F1 score
"""

import pandas as pd
import re

df = pd.read_csv("captions.csv")

# Check for missing values
#df.isna().any()
#df.isna().sum()

# Clean the data
def clean_text(text):
    text = str(text).lower().strip()
    text = re.sub(r"http\S+|www\S+", "", text)  # Removes URLs
    text = re.sub(r"\s+", " ", text)  # Cleans up extra spaces
    return text

df['clean_caption'] = df['caption'].astype(str).apply(clean_text)

print(df)

# Explore dataset
print("Dataset shape:", df.shape)
print("Number of unique accounts:", df['username'].nunique())

# New feature: number of words in each caption
df['caption_length'] = df['clean_caption'].apply(lambda x: len(x.split()))
print("Average caption length:", df['caption_length'].mean())

if 'account_type' in df.columns:
  print(df['account_type'].value_counts())
  print(df['account_type'].unique())

# Train/Validation/Test Split
from sklearn.model_selection import train_test_split

accounts = df['username'].unique()

# Split accounts into train (80%) and test(20%)
train_acc, test_acc = train_test_split(accounts, test_size = 0.2, random_state = 50)

# Split remaining 80% into train (70%) and validation (10%)
train_acc, val_acc = train_test_split(train_acc, test_size = 0.125, random_state = 50)

# Create datasets based on account username
train_df = df[df['username'].isin(train_acc)]
val_df = df[df['username'].isin(val_acc)]
test_df = df[df['username'].isin(test_acc)]

# Class balance check
print("Label counts:")  # Overall distribution of labels
print(df['label'].value_counts())

# Check label distribution in each split
print("\nTrain label counts:")
print(train_df['label'].value_counts())

print("\nValidation label counts:")
print(val_df['label'].value_counts())

print("\nTest label counts:")
print(test_df['label'].value_counts())

# Baseline model
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, f1_score, recall_score, precision_score, accuracy_score

vectorizer = TfidfVectorizer(max_features = 5000)

X_train = vectorizer.fit_transform(train_df['clean_caption'])
X_val = vectorizer.transform(val_df['clean_caption'])
X_test = vectorizer.transform(test_df['clean_caption'])

y_train = train_df['label']
y_val = val_df['label']
y_test = test_df['label']

model = LogisticRegression(max_iter = 1000)
model.fit(X_train, y_train)

# Validation evaluation
y_val_pred = model.predict(X_val)
print("Validation F1:", f1_score(y_val, y_val_pred, average = 'macro'))

# Test evaluation
y_pred = model.predict(X_test)

# Breakdown of performance per class
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Evaluation metrics
print("F1 Score:", f1_score(y_test, y_pred, average = 'macro'))
print("Recall:", recall_score(y_test, y_pred, average = 'macro'))
print("Precision:", precision_score(y_test, y_pred, average = 'macro'))
print("Accuracy:", accuracy_score(y_test, y_pred))

# Confusion matrix
from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize = (8, 6))
sns.heatmap(cm, annot = True, fmt = 'd', cmap = 'Blues', cbar = False)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title("Confusion Matrix")
plt.show()

# Group comparison
inf_test = test_df[test_df['account_type'] == 'influencer'] # Split test set
pol_test = test_df[test_df['account_type'] == 'politician']

print("Influencer test examples:", len(inf_test))
print("Politician test examples:", len(pol_test))

X_inf = vectorizer.transform(inf_test['clean_caption'])
y_inf = inf_test['label']

X_pol = vectorizer.transform(pol_test['clean_caption'])
y_pol = pol_test['label']

# Predict for each group
y_inf_pred = model.predict(X_inf)
y_pol_pred = model.predict(X_pol)

# Influencer performance
print("Influencer F1 Score:", f1_score(y_inf, y_inf_pred, average = 'macro'))
print("Influencer Accuracy:", accuracy_score(y_inf, y_inf_pred))

# Politician performance
print("Politician F1 Score:", f1_score(y_pol, y_pol_pred, average = 'macro'))
print("Politician Accuracy:", accuracy_score(y_pol, y_pol_pred))

"""### 2) Fine-tuned BERT classifier"""

from transformers import BertTokenizer, BertForSequenceClassification, Trainer, TrainingArguments
from datasets import Dataset
import numpy as np
import torch
from sklearn.metrics import f1_score, accuracy_score
import matplotlib.pyplot

# Convert pandas dataset to HuggingFace Dataset
train_dataset = Dataset.from_pandas(train_df[['clean_caption', 'label']])
val_dataset = Dataset.from_pandas(val_df[['clean_caption', 'label']])
test_dataset = Dataset.from_pandas(test_df[['clean_caption', 'label']])

# BERT tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

def tokenize(example):
  return tokenizer(example['clean_caption'], paddings='max_length', truncation=True, max_length=150)

train_dataset = train_dataset.map(tokenize, batched=True)
val_dataset = val_dataset.map(tokenize, batched=True)
test_dataset = test_dataset.map(tokenize, batched=True)

# Format for PyTorch
train_dataset.set_format(type='torch', columns=['input_ids', 'attention_mask', 'label'])
val_dataset.set_format(type='torch', columns=['input_ids', 'attention_mask', 'label'])
test_dataset.set_format(type='torch', columns=['input_ids', 'attention_mask', 'label'])

# Load BERT model
model = BertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=2)

# Defining the computation of the metrics
def compute_metrics(eval_pred):
  logits, labels = eval_pred
  preds = np.argmax(logits, axis=-1)
  return{
      'f1': f1_score(labels, preds, average='macro'),
      "accuracy": accuracy_score(labels, preds)
  }

# Training setup
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir='./results',
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    # evaluation_strategy="epoch",
    logging_strategy="epoch",
    save_strategy="no"
)

from transformers import DataCollatorWithPadding

# Create a collator
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

# Adding a Trainer
from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    data_collator=data_collator, # dynamically pads each batch
    compute_metrics=compute_metrics
)

trainer.train()

# Plot the loss curve
logs = trainer.state.log_history

train_losses = [log["loss"] for log in logs if "loss" in log]

plt.plot(train_losses)
plt.xlabel("Epoch")
plt.ylabel("Training Loss")
plt.title("BERT Training Loss Curve")
plt.show()

# Classification Report
from sklearn.metrics import classification_report

print(classification_report(y_true, y_pred))

# BERT Group Comparison
test_df = test_df.reset_index(drop=True)
test_df['pred'] = y_pred

inf = test_df[test_df['account_type'] == 'influencer']
pol = test_df[test_df['account_type'] == 'politician']

from sklearn.metrics import f1_score, accuracy_score

print("Influencer F1:", f1_score(inf['label'], inf['pred'], average='macro'))
print("Influencer Accuracy:", accuracy_score(inf['label'], inf['pred']))

print("Politician F1:", f1_score(pol['label'], pol['pred'], average='macro'))
print("Politician Accuracy:", accuracy_score(pol['label'], pol['pred']))
